[package]
name = "bls-sig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeropool-bn = {  version = "0.5.11", features = [] }
sha2 = "0.10.6"