[package]
name = "seda-sigs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
blsttc = {version = "7.1.0"}
getrandom = {version = "0.2.8", features = ["js"]}

